//! nlib's wire records, generated by `build.rs` from
//! `third_party/nlib/include/nlib/common.h`. See that build script for what
//! the generated code is asserted to hold.

// The bindings carry the header's whole vocabulary, of which a publisher uses
// the part its feed can express.
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/nlib.rs"));

pub use self::root::nlib::*;
